<template>
  <div class="panel right-panel">
    <section class="panel-block panel-block--summary">
      <div class="panel-block__header">
        <div>
          <div class="panel-kicker">车辆任务单</div>
          <h2 class="panel-title">轨迹对比分析</h2>
          <p class="panel-subtitle">选中任务单后自动加载轨迹并展示对比结果</p>
        </div>
        <div class="status-pill">{{ taskOrder.orderNo ? taskOrderStatusLabel : '等待选择' }}</div>
      </div>

      <div class="meta-grid">
        <div class="meta-item">
          <span class="meta-label">车牌</span>
          <span class="meta-value">{{ plateNumber || '未选择车辆' }}</span>
        </div>
        <div class="meta-item">
          <span class="meta-label">设备号</span>
          <span class="meta-value">{{ deviceNo || '--' }}</span>
        </div>
      </div>
    </section>

    <section class="panel-block panel-block--task">
      <div class="panel-block__header">
        <div>
          <div class="panel-kicker">任务上下文</div>
          <div class="panel-title">车辆任务单信息</div>
        </div>
        <div class="status-inline">{{ trajectorySummary.pointCount ? `${trajectorySummary.pointCount} 个轨迹点` : '等待任务单' }}</div>
      </div>

      <div class="task-grid">
        <article class="task-stat">
          <span class="task-stat__label">任务单号</span>
          <span class="task-stat__value">{{ taskOrder.orderNo || '--' }}</span>
        </article>
        <article class="task-stat">
          <span class="task-stat__label">任务状态</span>
          <span class="task-stat__value">{{ taskOrderStatusLabel }}</span>
        </article>
        <article class="task-stat">
          <span class="task-stat__label">作业围栏</span>
          <span class="task-stat__value">{{ taskOrder.fenceName || '--' }}</span>
        </article>
        <article class="task-stat">
          <span class="task-stat__label">作业类型</span>
          <span class="task-stat__value">{{ taskOrder.workModeText || '--' }}</span>
        </article>
        <article class="task-stat">
          <span class="task-stat__label">任务开始</span>
          <span class="task-stat__value">{{ formatDateTime(taskOrder.taskStartTime) || '--' }}</span>
        </article>
        <article class="task-stat">
          <span class="task-stat__label">自动生成</span>
          <span class="task-stat__value">{{ taskOrder.isAutoGenerateDaily ? '是' : '否' }}</span>
        </article>
      </div>

      <div v-if="trajectorySummary.startTime || trajectorySummary.endTime" class="task-note">
        轨迹区间：{{ formatDateTime(trajectorySummary.startTime) || '--' }} - {{ formatDateTime(trajectorySummary.endTime) || '--' }}
      </div>
    </section>

    <section class="panel-block" v-loading="analysisLoading">
      <div class="panel-block__header">
        <div>
          <div class="panel-kicker">轨迹对比</div>
          <div class="panel-title">分析结果</div>
        </div>
        <div class="status-inline">
          {{ analysisLoading ? '分析中' : analysisSummary ? '已完成' : '等待分析' }}
        </div>
      </div>

      <div v-if="analysisSummary" class="analysis-layout">
        <div class="analysis-stats">
          <article v-for="item in actualAnalysisStats" :key="item.label" class="analysis-stat">
            <span class="analysis-stat__label">{{ item.label }}</span>
            <span class="analysis-stat__value">{{ item.value }}</span>
          </article>
        </div>

        <div class="analysis-stats">
          <article v-for="item in compareAnalysisStats" :key="item.label" class="analysis-stat">
            <span class="analysis-stat__label">{{ item.label }}</span>
            <span class="analysis-stat__value">{{ item.value }}</span>
          </article>
        </div>

        <div v-if="analysisFence" class="fence-card">
          <div class="fence-card__head">
            <span>围栏结果</span>
            <span>{{ formatPercent(analysisFence.inside_ratio) }}</span>
          </div>
          <p class="fence-card__body">
            {{
              analysisFence?.issues?.length
                ? '发现异常点，建议检查围栏边界或轨迹偏移。'
                : '轨迹与围栏匹配正常。'
            }}
          </p>
          <div v-if="analysisFence?.issues?.length" class="analysis-issues">
            <div v-for="(issue, index) in analysisFence.issues" :key="`${issue}-${index}`" class="analysis-issue">
              {{ issue }}
            </div>
          </div>
        </div>

        <el-timeline v-if="analysisTimeline.length" class="analysis-timeline">
          <el-timeline-item
            v-for="item in analysisTimeline"
            :key="`${item.time}-${item.type}-${item.label}`"
            :timestamp="item.time"
            :type="timelineType(item.type)"
          >
            <div class="timeline-item">
              <span class="timeline-item__label">{{ timelineLabel(item) }}</span>
              <span v-for="meta in timelineMeta(item)" :key="meta" class="timeline-item__meta">{{ meta }}</span>
            </div>
          </el-timeline-item>
        </el-timeline>
      </div>

      <el-empty v-else description="选中车辆任务单后自动展示轨迹对比分析" />
    </section>

  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { ElNotification } from 'element-plus';
import { formatDateTimeLocal, toDate } from '@/utils/datetime';
import eventBus, { EventTypes } from '@/utils/eventBus';
import { fetchTrajectory, fetchTrajectoryAnalysis } from '@/api/vehicle';

type TaskOrder = {
  orderNo: string;
  status: string;
  vehicleName: string;
  licensePlate: string;
  deviceNo: string;
  fenceName: string;
  workModeText: string;
  taskStartTime: string | Date | null;
  isAutoGenerateDaily: boolean;
  taskStatusText: string;
};

export default defineComponent({
  name: 'TrajectoryFooter',
  components: {},
  data() {
    return {
      plateNumber: '',
      deviceNo: '',
      taskOrder: {
        orderNo: '',
        status: '',
        vehicleName: '',
        licensePlate: '',
        deviceNo: '',
        fenceName: '',
        workModeText: '',
        taskStartTime: null,
        isAutoGenerateDaily: false,
        taskStatusText: '等待选择',
      } as TaskOrder,
      trajectorySummary: {
        pointCount: 0,
        startTime: null as string | Date | null,
        endTime: null as string | Date | null,
      },
      analysisLoading: false,
      analysisSummary: null as null | {
        point_count: number;
        duration_seconds: number;
        distance_m: number;
        avg_speed_kmh: number;
        max_speed_kmh: number;
        stop_count: number;
      },
      analysisFence: null as null | {
        inside_ratio: number;
        issues?: string[];
      },
      analysisTimeline: [] as Array<{ time: string; type: string; label: string }>,
      analysisRequestId: 0,
    };
  },
  mounted() {
    eventBus.on(EventTypes.VehicleSelected, this.handleVehicleSelected);
  },
  beforeUnmount() {
    eventBus.off(EventTypes.VehicleSelected, this.handleVehicleSelected);
  },
  methods: {
    resetAnalysis() {
      this.analysisSummary = null;
      this.analysisFence = null;
      this.analysisTimeline = [];
      this.trajectorySummary = {
        pointCount: 0,
        startTime: null,
        endTime: null,
      };
    },
    handleVehicleSelected(detail: any) {
      const plate = detail.licensePlate || detail.license_plate || detail.vehicle_name || '';
      const deviceNo = detail.deviceNo || detail.device_no || '';
      if (plate) {
        this.plateNumber = plate;
      }
      if (deviceNo) {
        this.deviceNo = String(deviceNo);
      }
      this.taskOrder = this.normalizeTaskOrder(detail);
      if (this.deviceNo && (this.taskOrder.orderNo || this.taskOrder.taskStartTime)) {
        this.loadTaskOrderTrajectoryCompare(detail);
      } else {
        this.analysisRequestId += 1;
        this.analysisLoading = false;
        this.resetAnalysis();
        eventBus.emit(EventTypes.TrajectoryFetched, { deviceNo: this.deviceNo, points: [] });
      }
    },
    normalizeTaskOrder(detail: any): TaskOrder {
      const rawTask = detail?.rawTask || detail || {};
      const taskStartTime =
        rawTask?.taskStartTime ||
        rawTask?.task_start_time ||
        rawTask?.startTime ||
        rawTask?.start_time ||
        rawTask?.created_at ||
        rawTask?.createdAt ||
        detail?.taskStartTime ||
        detail?.task_start_time ||
        null;
      const status = String(rawTask?.taskStatus || rawTask?.status || detail?.taskStatus || detail?.status || 'draft').trim();
      const orderNo = String(detail?.taskOrderNo || rawTask?.orderNo || rawTask?.order_no || '').trim();
      const hasTaskContext = !!(
        orderNo ||
        taskStartTime ||
        rawTask?.fenceName ||
        rawTask?.fence_name ||
        rawTask?.work_fence_name ||
        rawTask?.workModeText ||
        rawTask?.work_mode_text
      );
      return {
        orderNo,
        status,
        vehicleName: String(detail?.vehicleName || rawTask?.vehicleName || rawTask?.vehicle_name || '').trim(),
        licensePlate: String(detail?.licensePlate || rawTask?.licensePlate || rawTask?.license_plate || '').trim(),
        deviceNo: String(detail?.deviceNo || rawTask?.deviceNo || rawTask?.device_no || '').trim(),
        fenceName: String(detail?.fenceName || rawTask?.fenceName || rawTask?.fence_name || rawTask?.work_fence_name || '').trim(),
        workModeText: String(detail?.workModeText || rawTask?.workModeText || rawTask?.work_mode_text || '').trim(),
        taskStartTime,
        isAutoGenerateDaily: Number(detail?.isAutoGenerateDaily || rawTask?.isAutoGenerateDaily || rawTask?.is_auto_generate_daily || 0) === 1,
        taskStatusText: hasTaskContext ? this.formatTaskStatus(status) : '等待选择',
      };
    },
    formatTaskStatus(status: string) {
      const map: Record<string, string> = {
        draft: '草稿',
        published: '已发布',
        executing: '执行中',
        finished: '已完成',
        checked: '已验收',
        cancelled: '已取消',
      };
      return map[String(status || '').toLowerCase()] || status || '待命';
    },
    async loadTaskOrderTrajectoryCompare(detail: any) {
      const task = this.normalizeTaskOrder(detail);
      const range = this.resolveTaskRange(task.taskStartTime);
      if (!range.startTime || !range.endTime) {
        this.resetAnalysis();
        return;
      }
      const requestId = ++this.analysisRequestId;
      this.analysisLoading = true;
      try {
        const params = {
          deviceNo: this.deviceNo,
          startTime: String(range.startTime),
          endTime: String(range.endTime),
        };
        const trajectoryPayload = await fetchTrajectory(params);
        const points = this.normalizeTrajectory(trajectoryPayload);
        if (requestId !== this.analysisRequestId) return;
        this.trajectorySummary = this.buildTrajectorySummary(points, range);
        eventBus.emit(EventTypes.TrajectoryFetched, { deviceNo: this.deviceNo, points });

        const analysisPayload = await fetchTrajectoryAnalysis(params);
        if (requestId !== this.analysisRequestId) return;
        const fence = analysisPayload?.data?.fence ?? null;
        const timeline = Array.isArray(analysisPayload?.data?.timeline) ? analysisPayload.data.timeline : [];
        const fenceTimeline = Array.isArray(fence?.timeline) ? fence.timeline : [];
        this.analysisSummary = analysisPayload?.data?.summary ?? null;
        this.analysisFence = fence;
        this.analysisTimeline = this.mergeTimeline(timeline, fenceTimeline);
        eventBus.emit(EventTypes.TrajectoryAnalyzed, {
          deviceNo: this.deviceNo,
          summary: this.analysisSummary,
          fence: this.analysisFence,
          timeline: this.analysisTimeline,
          taskOrder: this.taskOrder,
          trajectorySummary: this.trajectorySummary,
        });
        if (!points.length) {
          ElNotification({
            title: '提示',
            message: '未查询到该任务单对应的轨迹点',
            type: 'info',
          });
        }
      } catch (error: any) {
        if (requestId !== this.analysisRequestId) return;
        const message = error?.message || '任务单轨迹对比分析失败';
        ElNotification({ title: '错误', message, type: 'error' });
        this.resetAnalysis();
        eventBus.emit(EventTypes.TrajectoryFetched, { deviceNo: this.deviceNo, points: [] });
      } finally {
        if (requestId === this.analysisRequestId) {
          this.analysisLoading = false;
        }
      }
    },
    resolveTaskRange(taskStartTime: string | Date | null) {
      const date = toDate(taskStartTime) || new Date();
      const start = new Date(date.getFullYear(), date.getMonth(), date.getDate(), 0, 0, 0, 0);
      const end = new Date(date.getFullYear(), date.getMonth(), date.getDate(), 23, 59, 59, 999);
      return {
        startTime: start.getTime(),
        endTime: end.getTime(),
      };
    },
    normalizeTrajectory(payload: any) {
      const list =
        Array.isArray(payload?.data?.list)
          ? payload.data.list
          : Array.isArray(payload?.data)
            ? payload.data
            : Array.isArray(payload)
              ? payload
              : payload?.data
                ? [payload.data]
                : [];
      return list
        .map((item: any, index: number) => {
          const lon = Number(item?.lon ?? item?.lng ?? item?.longitude);
          const lat = Number(item?.lat ?? item?.latitude);
          if (!Number.isFinite(lon) || !Number.isFinite(lat)) return null;
          return {
            index,
            position: [lon, lat],
            raw: item,
            time: item?.ts || item?.timer || '',
            lon,
            lat,
            speed: item?.speed ?? item?.calculatedSpeed ?? null,
            altitude: item?.ASL ?? item?.DEM ?? null,
          };
        })
        .filter(Boolean);
    },
    buildTrajectorySummary(points: any[], range: { startTime: number | string; endTime: number | string }) {
      const validTimes = (Array.isArray(points) ? points : [])
        .map((point) => point?.time)
        .filter(Boolean);
      return {
        pointCount: Array.isArray(points) ? points.length : 0,
        startTime: validTimes[0] || range.startTime || null,
        endTime: validTimes[validTimes.length - 1] || range.endTime || null,
      };
    },
    formatDistance(distance: number) {
      if (!Number.isFinite(distance)) return '-';
      if (distance >= 1000) {
        return `${(distance / 1000).toFixed(2)} km`;
      }
      return `${distance.toFixed(0)} m`;
    },
    formatDuration(seconds: number) {
      if (!Number.isFinite(seconds) || seconds <= 0) return '0s';
      const hours = Math.floor(seconds / 3600);
      const minutes = Math.floor((seconds % 3600) / 60);
      const secs = Math.floor(seconds % 60);
      const parts = [];
      if (hours) parts.push(`${hours}h`);
      if (minutes) parts.push(`${minutes}m`);
      if (secs || !parts.length) parts.push(`${secs}s`);
      return parts.join(' ');
    },
    formatPercent(value?: number) {
      if (typeof value !== 'number' || Number.isNaN(value)) return '-';
      return `${value.toFixed(1)}%`;
    },
    formatDateTime(value: any) {
      const date = toDate(value);
      return date ? formatDateTimeLocal(date) : '';
    },
    timelineType(type: string) {
      if (type === 'start') return 'primary';
      if (type === 'end') return 'success';
      if (type === 'stop') return 'warning';
      if (type === 'overspeed') return 'danger';
      if (type === 'fence_in') return 'success';
      if (type === 'fence_out') return 'danger';
      return 'info';
    },
    timelineLabel(item: any) {
      if (item?.label) return item.label;
      if (item?.type === 'fence_in') return '进入围栏';
      if (item?.type === 'fence_out') return '离开围栏';
      if (item?.type === 'start') return '开始';
      if (item?.type === 'end') return '结束';
      if (item?.type === 'stop') return '停车';
      if (item?.type === 'overspeed') return '超速';
      return '事件';
    },
    timelineMeta(item: any) {
      const detail = item?.detail || {};
      const lines: string[] = [];
      if (detail.fence_name) {
        lines.push(`围栏：${detail.fence_name}`);
      }
      if (detail.lon !== undefined && detail.lat !== undefined) {
        lines.push(`位置：${this.formatCoord(detail.lon, detail.lat)}`);
      }
      if (detail.stay_seconds !== undefined) {
        lines.push(`停留：${this.formatDuration(detail.stay_seconds)}`);
      }
      if (detail.duration !== undefined && item.type !== 'stop') {
        lines.push(`持续：${this.formatDuration(detail.duration)}`);
      }
      if (detail.max_speed !== undefined) {
        lines.push(`最高速度：${Number(detail.max_speed).toFixed(1)} km/h`);
      }
      return lines;
    },
    mergeTimeline(primary: any[], extra: any[]) {
      const list = [...(Array.isArray(primary) ? primary : []), ...(Array.isArray(extra) ? extra : [])];
      if (!list.length) return [];
      const seen = new Set<string>();
      const merged: any[] = [];
      list.forEach((item) => {
        const key = `${item?.time ?? ''}|${item?.type ?? ''}|${item?.label ?? ''}`;
        if (seen.has(key)) return;
        seen.add(key);
        merged.push(item);
      });
      merged.sort((a, b) => String(a?.time ?? '').localeCompare(String(b?.time ?? '')));
      return merged;
    },
    formatCoord(lon: number, lat: number) {
      const lonNum = Number(lon);
      const latNum = Number(lat);
      if (!Number.isFinite(lonNum) || !Number.isFinite(latNum)) return '-';
      return `${lonNum.toFixed(6)}, ${latNum.toFixed(6)}`;
    },
  },
  computed: {
    taskOrderStatusLabel(): string {
      if (!this.taskOrder?.orderNo) return '等待选择';
      return this.taskOrder.taskStatusText || this.formatTaskStatus(this.taskOrder.status);
    },
    actualAnalysisStats() {
      if (!this.analysisSummary) return [];
      const stats = this.analysisSummary;
      return [
        { label: '实际里程', value: this.formatDistance(stats.distance_m) },
        { label: '实际时长', value: this.formatDuration(stats.duration_seconds) },
        { label: '平均速度', value: `${stats.avg_speed_kmh.toFixed(1)} km/h` },
        { label: '最高速度', value: `${stats.max_speed_kmh.toFixed(1)} km/h` },
      ];
    },
    compareAnalysisStats() {
      if (!this.analysisSummary) return [];
      const stats = this.analysisSummary;
      const compareLabel = this.analysisFence?.issues?.length ? '路线贴合率' : '围栏贴合率';
      return [
        { label: compareLabel, value: this.formatPercent(this.analysisFence?.inside_ratio) },
        { label: '异常数量', value: String(this.analysisFence?.issues?.length ?? 0) },
        { label: '停车次数', value: String(stats.stop_count) },
      ];
    },
  },
});
</script>

<style scoped>
.panel {
  width: 100%;
  height: 100%;
  min-height: 0;
  box-sizing: border-box;
  padding: 10px;
  display: flex;
  flex-direction: column;
  gap: 10px;
  overflow: auto;
  scrollbar-width: thin;
  scrollbar-color: rgba(94, 106, 122, 0.9) rgba(8, 12, 20, 0.88);
  color: #dbe4f0;
  background: linear-gradient(180deg, #060b14 0%, #040810 100%);
}

.panel::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}

.panel::-webkit-scrollbar-track {
  background: rgba(8, 12, 20, 0.88);
}

.panel::-webkit-scrollbar-thumb {
  border-radius: 999px;
  border: 1px solid rgba(8, 12, 20, 0.88);
  background: rgba(94, 106, 122, 0.68);
}

.panel::-webkit-scrollbar-thumb:hover {
  background: rgba(120, 133, 149, 0.86);
}

.panel::-webkit-scrollbar-corner {
  background: rgba(8, 12, 20, 0.88);
}

.panel-block {
  padding: 12px 0;
  border-bottom: 1px solid rgba(148, 163, 184, 0.08);
}

.panel-block:last-child {
  border-bottom: none;
}

.panel-block__header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
}

.panel-kicker {
  font-size: 11px;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: #7dd3fc;
}

.panel-title {
  margin: 6px 0 4px;
  font-size: 18px;
  line-height: 1.2;
  color: #f8fafc;
  font-weight: 700;
}

.panel-subtitle {
  margin: 0;
  font-size: 12px;
  color: #94a3b8;
}

.status-pill {
  flex: 0 0 auto;
  padding: 6px 10px;
  border-radius: 999px;
  background: rgba(59, 130, 246, 0.12);
  border: 1px solid rgba(59, 130, 246, 0.2);
  color: #bfdbfe;
  font-size: 12px;
  white-space: nowrap;
}

.meta-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 10px;
  margin-top: 14px;
}

.meta-item {
  padding: 10px 0;
  border-bottom: 1px solid rgba(148, 163, 184, 0.06);
  min-width: 0;
}

.meta-item:last-child {
  border-bottom: none;
}

.meta-label {
  display: block;
  margin-bottom: 6px;
  font-size: 11px;
  color: #64748b;
}

.meta-value {
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 13px;
  font-weight: 600;
  color: #e2e8f0;
}

.task-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 10px;
}

.task-stat {
  padding: 12px 0;
  border-bottom: 1px solid rgba(148, 163, 184, 0.06);
}

.task-stat:last-child {
  border-bottom: none;
}

.task-stat__label {
  display: block;
  font-size: 12px;
  color: #94a3b8;
}

.task-stat__value {
  display: block;
  margin-top: 6px;
  font-size: 14px;
  font-weight: 600;
  color: #e2e8f0;
}

.task-note {
  margin-top: 10px;
  font-size: 12px;
  line-height: 1.6;
  color: #94a3b8;
}

.panel-actions {
  display: flex;
  justify-content: flex-end;
  flex-wrap: wrap;
  gap: 8px;
}

.status-inline {
  font-size: 12px;
  color: #94a3b8;
  white-space: nowrap;
}

.analysis-layout {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.analysis-stats {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 10px;
}

.analysis-stat {
  padding: 12px 0;
  border-bottom: 1px solid rgba(148, 163, 184, 0.06);
}

.analysis-stat:last-child {
  border-bottom: none;
}

.analysis-stat__label {
  display: block;
  font-size: 12px;
  color: #94a3b8;
}

.analysis-stat__value {
  display: block;
  margin-top: 6px;
  font-size: 16px;
  font-weight: 700;
  color: #f8fafc;
}

.fence-card {
  padding: 12px;
  border-left: 2px solid rgba(59, 130, 246, 0.65);
  background: rgba(255, 255, 255, 0.02);
}

.fence-card__head {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  font-size: 12px;
  color: #cbd5e1;
}

.fence-card__body {
  margin: 6px 0 0;
  font-size: 12px;
  line-height: 1.6;
  color: #94a3b8;
}

.analysis-issues {
  margin-top: 10px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.analysis-issue {
  padding: 8px 10px;
  border-left: 2px solid rgba(249, 115, 22, 0.45);
  background: rgba(249, 115, 22, 0.06);
  color: #fdba74;
  font-size: 12px;
  line-height: 1.5;
}

.analysis-timeline {
  padding-left: 4px;
}

.timeline-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.timeline-item__label {
  font-size: 13px;
  font-weight: 600;
  color: #e5e7eb;
}

.timeline-item__meta {
  font-size: 12px;
  line-height: 1.5;
  color: #94a3b8;
}

:deep(.el-loading-mask) {
  background-color: rgba(2, 6, 23, 0.72);
}

:deep(.el-empty__description) {
  color: #94a3b8;
}

:deep(.el-timeline) {
  --el-timeline-node-color: #2563eb;
  --el-timeline-line-color: rgba(148, 163, 184, 0.18);
  --el-timeline-text-color: #e2e8f0;
  --el-timeline-timestamp-color: #94a3b8;
  color: #e2e8f0;
}

:deep(.el-timeline-item__tail) {
  background-color: rgba(148, 163, 184, 0.18) !important;
}

:deep(.el-timeline-item__timestamp) {
  color: #94a3b8 !important;
  font-size: 12px;
}

:deep(.el-timeline-item__node) {
  background-color: #0b1220 !important;
  border-color: rgba(37, 99, 235, 0.8) !important;
}

.panel :deep(.el-divider) {
  border-color: rgba(148, 163, 184, 0.08);
}

@media (max-width: 1280px) {
  .meta-grid,
  .analysis-stats,
  .task-grid {
    grid-template-columns: 1fr;
  }
}
</style>
