import { normalizeListResult, requestJson } from '@/api/http'

const TASK_ORDER_BASE_PATH = import.meta.env.VITE_DISPATCH_SIMPLE_TASK_PATH || '/dispatch-simple-tasks'

const nowText = () => new Date().toISOString().replace('T', ' ').slice(0, 19)

const buildFormBody = (payload = {}) => {
  const form = new URLSearchParams()
  Object.entries(payload).forEach(([key, value]) => {
    if (value === undefined || value === null || value === '') {
      return
    }
    form.append(key, String(value))
  })
  return form.toString()
}

const postForm = (path, payload = {}) =>
  requestJson(path, {
    method: 'POST',
    body: buildFormBody(payload),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
    },
  })

const normalizeTaskOrder = (item = {}, index = 0) => {
  const id = item.id ?? item.task_order_id ?? item.taskOrderId ?? item.order_id ?? item.orderId
  const licensePlate = item.license_plate ?? item.licensePlate ?? item.plate_no ?? item.plate ?? ''
  const workFenceName =
    item.work_fence_name ??
    item.workFenceName ??
    item.fence_name ??
    item.fenceName ??
    item.work_area ??
    ''
  const workModeText =
    item.work_mode_text ??
    item.workModeText ??
    item.work_mode ??
    item.workMode ??
    item.job_type ??
    item.jobType ??
    ''
  const startTime =
    item.task_start_time ??
    item.taskStartTime ??
    item.start_time ??
    item.startTime ??
    item.begin_time ??
    item.beginTime ??
    item.plan_start_time ??
    item.planStartTime ??
    item.dispatch_start_time ??
    item.dispatchStartTime ??
    item.schedule_start_time ??
    item.scheduleStartTime ??
    item.created_at ??
    item.createdAt ??
    nowText()

  const status =
    item.status ??
    item.task_status ??
    item.taskStatus ??
    item.order_status ??
    item.orderStatus ??
    item.workflow_status ??
    item.workflowStatus ??
    'draft'

  return {
    id: id ?? `task_${index}`,
    order_no: item.order_no ?? item.orderNo ?? '',
    order_type: item.order_type ?? item.orderType ?? item.job_type ?? item.jobType ?? '',
    status,
    vehicle_id: item.vehicle_id ?? item.vehicleId ?? '',
    vehicle_name: item.vehicle_name ?? item.vehicleName ?? '',
    license_plate: licensePlate,
    fence_id: Number(item.fence_id ?? item.fenceId ?? 0),
    fence_name: item.fence_name ?? item.fenceName ?? workFenceName,
    work_fence_name: workFenceName,
    work_mode_text: workModeText,
    is_auto_generate_daily: Number(item.is_auto_generate_daily ?? item.isAutoGenerateDaily ?? 0) === 1 ? 1 : 0,
    task_start_time: startTime,
    remark: item.remark ?? item.memo ?? item.note ?? item.description ?? '',
    created_by: item.created_by ?? item.createdBy ?? '',
    created_name: item.created_name ?? item.createdName ?? '',
    is_deleted: item.is_deleted ?? item.isDeleted ?? 0,
    updated_at: item.updated_at ?? item.updatedAt ?? startTime,
    created_at: item.created_at ?? item.createdAt ?? startTime,
    start_time: startTime,
  }
}

export const fetchTaskOrders = ({ page = 1, pageSize = 200, status = '', keyword = '' } = {}) =>
  requestJson(`${TASK_ORDER_BASE_PATH}/index`, {
    params: {
      page,
      pageSize,
      status: status || undefined,
      keyword: keyword || undefined,
    },
  }).then((payload) => {
    const { list, total } = normalizeListResult(payload)
    return {
      list: (list || []).map((item, index) => normalizeTaskOrder(item, index)),
      total,
    }
  })

export const createTaskOrder = (payload = {}) =>
  postForm(`${TASK_ORDER_BASE_PATH}/save`, {
    ...payload,
    license_plate: String(payload.license_plate || '').trim(),
    work_fence_name: String(payload.work_fence_name || payload.fence_name || '').trim(),
    fence_name: String(payload.fence_name || payload.work_fence_name || '').trim(),
    work_mode_text: String(payload.work_mode_text || '').trim(),
    is_auto_generate_daily: Number(payload.is_auto_generate_daily || 0) === 1 ? 1 : 0,
    task_start_time: String(payload.task_start_time || payload.start_time || '').trim(),
    status: String(payload.status || 'draft').trim(),
    remark: String(payload.remark || '').trim(),
  })

export const updateTaskOrder = (id, payload = {}) =>
  postForm(`${TASK_ORDER_BASE_PATH}/update`, {
    id,
    ...payload,
    license_plate: String(payload.license_plate || '').trim(),
    work_fence_name: String(payload.work_fence_name || payload.fence_name || '').trim(),
    fence_name: String(payload.fence_name || payload.work_fence_name || '').trim(),
    work_mode_text: String(payload.work_mode_text || '').trim(),
    is_auto_generate_daily: Number(payload.is_auto_generate_daily || 0) === 1 ? 1 : 0,
    task_start_time: String(payload.task_start_time || payload.start_time || '').trim(),
    status: String(payload.status || 'draft').trim(),
    remark: String(payload.remark || '').trim(),
  })

export const deleteTaskOrder = (id) =>
  postForm(`${TASK_ORDER_BASE_PATH}/delete`, {
    id,
  })

export default {
  fetchTaskOrders,
  createTaskOrder,
  updateTaskOrder,
  deleteTaskOrder,
}
